tikv/rust-prometheus

.gitignore, .travis.yml, Cargo.toml, Makefile, proto/metrics.proto, src/counter.rs, src/desc.rs, src/errors.rs, src/lib.rs, src/metrics.rs, src/proto.rs, src/registry.rs, src/value.rs
@BusyJay @overvenus @qiuyesuifeng
=> *: initialization.

Makefile, examples/example_embed.rs, src/counter.rs, src/desc.rs, src/errors.rs, src/lib.rs, src/metrics.rs, src/registry.rs, src/value.rs, src/vec.rs
@BusyJay @overvenus 
PTAL @lucab
=> support metric vector

Cargo.toml, examples/example_hyper.rs
=> *: use released 0.9 hyper in cargo.

Cargo.toml, examples/example_embed.rs, examples/example_hyper.rs
=> Cargo: support publish

Cargo.toml, src/lib.rs, src/registry.rs
Resolved #13 
PTAL @siddontang @BusyJay
=> Add a global registry

examples/example_hyper.rs, src/encoder.rs, src/histogram.rs, src/lib.rs
Resolved #4 
Experimental support for histogram.
PTAL @siddontang @disksing @BusyJay
=> Add histogram

Cargo.toml
=> Cargo: use 0.2.0 for crate.

examples/example_hyper.rs, src/histogram.rs, src/lib.rs, src/macros.rs, src/metrics.rs, src/registry.rs
Resolved #26 
Resolved #14 
Example:
```rust
lazy_static! {
static ref COUNTER: Counter = register_counter_with!(
opts!(
"test_opt",
"test_opt_help",
labels!{
"test"=> "hello",
"foo"=> "bar",
"ans"=> "42",
}
)
);
}
fn main() {
COUNTER.inc();
println!("{:?}", COUNTER.get());
}
```
PTAL @siddontang @disksing @BusyJay
=> Add some macros

src/counter.rs, src/gauge.rs, src/histogram.rs, src/metrics.rs, src/registry.rs, src/value.rs, src/vec.rs
PTAL @overvenus @queenypingcap
=> *: add docs.

examples/example_embed.rs, src/counter.rs, src/encoder.rs, src/gauge.rs, src/histogram.rs, src/lib.rs, src/untyped.rs, src/vec.rs
Resolved #3 
PTAL @siddontang @disksing @BusyJay
=> untyped: add untyped

Cargo.toml, README.md
@queenypingcap  @overvenus 
PTAL @lucab
=> add readme

Cargo.toml, examples/example_hyper.rs, src/histogram.rs, src/lib.rs
=> histogram supports observe_duration. 

Cargo.toml, examples/example_hyper.rs, src/histogram.rs
Resolved #45
PTAL @siddontang @disksing @brian-brazil
=> *: add HistogramTimer

Cargo.toml, README.md, src/histogram.rs
=> histogram: bug fix, using custom buckets

Cargo.toml, examples/example_hyper.rs, src/histogram.rs
=> histogram: impl Drop for HistogramTimer

Cargo.toml, examples/example_push.rs, src/lib.rs, src/push.rs
=> Support push

src/vec.rs
=> use read lock first.

src/push.rs
`libc::gethostname` is not  available in Windows.
/cc @syepes
=> push: compiles in windows

src/vec.rs
Get a metric with labels that are arbitrarily ordered.
/cc @syepes
=> vec: get a metric with labels that are arbitrarily ordered

src/encoder.rs
=> encoder: remove no metrics error

Cargo.toml, src/counter.rs, src/encoder.rs, src/gauge.rs, src/histogram.rs, src/metrics.rs, src/registry.rs, src/vec.rs
A colletcor should be able to collect multiple metrics.
=> *: a collector collects multiple metrics

Makefile
=> Makefile: reformat only when has changes

src/registry.rs
=> registry: Use `is_none` instead of `if let None = ...`

Makefile, src/lib.rs, src/local.rs
Currently there is no way to declare a variable has type `LocalHistogram`.
@siddontang @overvenus PTAL
=> histogram: expose LocalHistogram

.travis.yml, examples/example_process_collector.rs, src/lib.rs, src/macros.rs, src/push.rs, src/registry.rs
=> Fix few clippy warnings

src/encoder/mod.rs, src/encoder/pb.rs, src/encoder/text.rs, src/errors.rs, src/histogram.rs, src/push.rs, src/vec.rs
PTAL @siddontang @disksing @BusyJay
=> encoder: static dispatch Write

Cargo.toml
For cargo package, we need include proto rs files. 
PTAL @overvenus @BusyJay
=> add publication package

src/encoder/text.rs, src/gauge.rs, src/histogram.rs, src/lib.rs, src/metrics.rs, src/process_collector.rs, src/push.rs, src/registry.rs, src/value.rs, src/vec.rs
* clean up workarounds
* remove allow(dead_code)
=> *: remove allow lints

Cargo.toml
+ Add package metadata.
+ Simplify dependency's version.
=> Bump to 0.3.2

src/histogram.rs, src/registry.rs
We need LocalHistgram impl Send.remove the unnecessary Rc wrap.
=> histogram: remove Rc in LocalHistogram

src/atomic64.rs, src/push.rs
Fix clippy warning `implicit_hasher`[0].
[0] https://rust-lang-nursery.github.io/rust-clippy/v0.0.166/index.html#implicit_hasher
CC #118
=> push: fix implicit hasher

Makefile, benches/counter.rs, benches/gauge.rs, benches/histogram.rs, examples/example_embed.rs, examples/example_hyper.rs, examples/example_process_collector.rs, examples/example_push.rs, rustfmt.toml, src/atomic64.rs, src/counter.rs, src/desc.rs, src/encoder/mod.rs, src/encoder/pb.rs, src/encoder/text.rs, src/errors.rs, src/gauge.rs, src/histogram.rs, src/lib.rs, src/metrics.rs, src/process_collector.rs, src/push.rs, src/registry.rs, src/value.rs, src/vec.rs
=> format codes

proto/metrics.rs, src/counter.rs, src/desc.rs, src/encoder/pb.rs, src/encoder/text.rs, src/gauge.rs, src/histogram.rs, src/lib.rs, src/process_collector.rs, src/push.rs
This PR fixed some clippy warnings.
=> *: fix clippy warning

Cargo.toml, src/atomic64.rs, src/lib.rs, src/vec.rs
refer #121 
PTAL @overvenus @BusyJay
=> use spinlock to improve the lock performance

src/push.rs
=> push: set timeout for http client

Cargo.toml, src/counter.rs
LocalCounter should impl Clone. Also, fixed some clippy warnings.
=> counter: impl Clone for LocalCounter

CHANGELOG.md, Cargo.toml, examples/example_embed.rs, src/counter.rs, src/errors.rs, src/process_collector.rs
Fix https://github.com/pingcap/rust-prometheus/issues/151
this simplifies and unifies the counter interface.
because it is a breaking change, a changelog file is introduced.
=> panic instead of error when decrease counter

README.md, src/counter.rs, src/desc.rs, src/encoder/mod.rs, src/encoder/pb.rs, src/encoder/text.rs, src/gauge.rs, src/histogram.rs, src/lib.rs, src/local.rs, src/macros.rs, src/metrics.rs, src/process_collector.rs, src/registry.rs, src/vec.rs
Many documentations are missing. This PR improves the documentation quality for the cover page (i.e. http://docs.rs/prometheus ).
=> Improve cover documentations

static-metric/Cargo.toml, static-metric/Makefile, static-metric/README.md, static-metric/examples/register_integration.rs, static-metric/src/lib.rs, static-metric/src/register_macro.rs
This can further simplify user code.
=> Introduce `register_static_xxx!` macros

examples/example_int_metrics.rs, src/atomic64/nightly.rs, src/histogram.rs, src/lib.rs, src/process_collector.rs, static-metric/src/builder.rs, static-metric/tests/metric.rs
nightly-2018-07-18, the same to TiKV's version.
=> Reformat using a recent rustfmt

.travis.yml, examples/example_hyper.rs, src/desc.rs, src/value.rs, static-metric/src/builder.rs, static-metric/src/lib.rs, static-metric/src/parser.rs, static-metric/src/util.rs
Clippy is now on stable! :tada: This is similar to https://github.com/pingcap/raft-rs/pull/124.
=> Use stable clippy

src/lib.rs
Add some additional documentation to the generated documentation.
=> Add some documentation examples.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/something-else.md, .github/PULL_REQUEST_TEMPLATE/bug_fix.md, .github/PULL_REQUEST_TEMPLATE/feature.md, .github/PULL_REQUEST_TEMPLATE/something-else.md
Same as:
* https://github.com/pingcap/fail-rs/pull/17
* https://github.com/pingcap/grpc-rs/pull/221
=> Create issue templates

src/metrics.rs
Just noticed it while browsing the docs :).
=> fix small typo in Opts method

Cargo.toml, benches/atomic.rs, benches/counter.rs, benches/gauge.rs, benches/histogram.rs, build.rs, examples/example_embed.rs, examples/example_hyper.rs, examples/example_process_collector.rs, examples/example_push.rs, proto/proto_model.rs, rustfmt.toml, src/counter.rs, src/desc.rs, src/encoder/mod.rs, src/encoder/pb.rs, src/encoder/text.rs, src/gauge.rs, src/histogram.rs, src/lib.rs, src/metrics.rs, src/process_collector.rs, src/push.rs, src/registry.rs, src/value.rs, src/vec.rs
Extracted from #227.
PTAL @breeswish
=> Update to 2018 edition

Cargo.toml, src/desc.rs
=> char::is_ascii has been stabilized

benches/counter.rs
Simulating that there are multiple threads accessing the same counter.
=> Add some benchmarks for concurrent counter access

Cargo.toml
Signed-off-by: wsc <386180127@qq.com>
update lazy_static to 1.3
=> update lazy_static to 1.3

src/counter.rs
Counters can only increase or be reset to zero on restart.
This adds support for soft resets at runtime, by implementing and
exposing reset-to-zero methods.
Ref: https://prometheus.io/docs/concepts/metric_types/#counter
=> counter: add support for runtime resets (zeroing)

src/histogram.rs
This augments histogram timers (both sync and unsync) with several
new features:
* timers can now return their duration on stop, in order for
consumers to use that as the input for further logic.
* timers can now be stopped and discarded, in order to (optionally)
not record their duration to the attached histogram.
All of the above come with corresponding tests.
=> histogram: augment timers

src/registry.rs
There was a bug in the label handling where every metric after the first
did not have labels applied.
We were calling Vec::append() with a mutable vec as the argument, and
doing so causes the elements to change ownership from the source to the
target vec.
This change fixes the problem by cloning the label vec and introducing a
test.
=> Fix bug in global label handling.

src/gauge.rs
This applies `rustfmt` to the whole project.
Signed-off-by: Luca BRUNO <luca.bruno@coreos.com>
=> gauge: apply rustfmt

Cargo.toml, src/gauge.rs
It seems to require protobuf.
Fixes #277.
=> Fix push feature dependencies

Cargo.toml, examples/example_custom_registry.rs, examples/example_hyper.rs, src/atomic64.rs, src/counter.rs, src/desc.rs, src/encoder/mod.rs, src/encoder/pb.rs, src/encoder/text.rs, src/errors.rs, src/gauge.rs, src/histogram.rs, src/lib.rs, src/metrics.rs, src/plain_model.rs, src/process_collector.rs, src/push.rs, src/registry.rs, src/value.rs, src/vec.rs, static-metric/examples/local.rs, static-metric/src/parser.rs
- Use failure instead of quick-error
- Fix some typos
- Reorder some import
=> Use thiserror instead of quick-error

src/push.rs
should I remove `StatusCode::ACCEPTED => Ok(())`?
=> accept 200 response code when pushing to pushgateway

src/histogram.rs
A implementation of  https://github.com/tikv/tikv/issues/6171
=> add method observe_closure_duration

src/counter.rs, src/histogram.rs, src/lib.rs, src/metrics.rs, static-metric/src/builder.rs
Add a LocalMetric trait for reason discussed in https://github.com/tikv/tikv/pull/6163
=> Add LocalMetric trait

Cargo.toml, README.md, examples/example_hyper.rs, src/push.rs
=> Update to reqwest 0.10

Cargo.toml, src/auto_flush.rs, src/lib.rs, src/metrics.rs, src/timer.rs, static-metric/Cargo.toml, static-metric/README.md, static-metric/examples/local.rs, static-metric/examples/make_auto_flush_static_counter.rs, static-metric/examples/make_auto_flush_static_metric_histogram.rs, static-metric/proc-macros/Cargo.toml, static-metric/proc-macros/src/auto_flush_builder.rs
What we need is a time cache updated periodically, it's so simple that
doesn't require a library. Besides current used library appears to have
a UAF problem.
Close #312.
=> *: remove coarse time

src/auto_flush.rs
Signed-off-by: Renkai <gaelookair@gmail.com>
=> bug fix: change return type of get

CHANGELOG.md, Cargo.toml, src/encoder/text.rs
@breeswish  , as discussed, I'd like to bump to a new version (so that I can take the latest changes).
=> Bump version 9.0.0

Cargo.toml
This updates all dependencies to their latest version.
=> cargo: update all dependencies

docs/release.md
This pull request documents the release process I have been following for the last couple of releases. While quite rudimentary I think some release process is better than no release process.
I welcome both suggestions in regards to the documentation as well as how to evolve the process itself.
Signed-off-by: Max Inden <mail@max-inden.de>
=> doc/release.md: Document release process

Cargo.toml
=> Update to tokio 1.0 and hyper 0.14

src/macros.rs
This PR allows to append optional comma after the last argument of those opts!/register! like macros.
=> Allow trailing commas on macros

README.md
This feature is going to get a lot of interest quickly https://github.com/rustsec/advisory-db/pull/2169
=> README.md: Document protobuf feature
