tikv/rust-prometheus

- src/macros.rs
Resolved #35 
@siddontang @disksing
> macros: add register vec macros

- src/registry.rs
- src/vec.rs
> Gather sort

- Cargo.toml
- src/desc.rs
- src/lib.rs
The regexes are copied from the Go client libraries; Go and the regex
crate both use RE2 syntax.
> validate metric and label names

- benches/benches.rs
- benches/gauge.rs
- benches/histogram.rs
Report:
```
test counter::bench_counter_no_labels                   ... bench:          44 ns/iter (+/- 2)
test counter::bench_counter_with_label_values           ... bench:         136 ns/iter (+/- 4)
test counter::bench_counter_with_mapped_labels          ... bench:         400 ns/iter (+/- 44)
test counter::bench_counter_with_prepared_mapped_labels ... bench:         250 ns/iter (+/- 4)
test gauge::bench_gauge_no_labels                       ... bench:          43 ns/iter (+/- 1)
test gauge::bench_gauge_with_label_values               ... bench:         131 ns/iter (+/- 7)
test histogram::bench_histogram_no_labels               ... bench:          52 ns/iter (+/- 12)
test histogram::bench_histogram_timer                   ... bench:         265 ns/iter (+/- 14)
test …
```
> bench: add gauge and histogram benchmarks

- src/histogram.rs
Previous Timer implementation clone Histogram Desc and Label names, which is not necessary and will cost bad performance. 
Before:
```
test histogram::bench_histogram_timer                   ... bench:         154 ns/iter (+/- 23)
```
Now
```
test histogram::bench_histogram_timer                   ... bench:          88 ns/iter (+/- 16)
```
@overvenus @disksing
> improve histogram clone performance

- src/push.rs
Clippy warns:
```
error: it is more idiomatic to loop over `collectors` instead of `collectors.into_iter()` [-D explicit-into-iter-loop]
--> src/push.rs:157:5
|
157 |     for bc in collectors.into_iter() {
|     ^
|
= help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#explicit_into_iter_loop
error: aborting due to previous error
```
> push: make clippy happy

- src/registry.rs
When we register a collector that returns multiple descriptors, registry will panic and leaves a message:
> panicked at 'attempt to add with overflow', src/registry.rs:61
[Integer overflow] is considered unsafe in rust. Rust checks it at both [compile time and runtime].
Although there are several ways to workaround, like [scoped-attributes] and [wrapping], ~~I would recommend [xor]. I think xor is enough in our use case.~~
Now, wrapping add.
PTAL @siddontang @disksing 
[xor]: https://doc.rust-lang.org/std/ops/trait.BitXor.html
[wrapping]: https://github.com/rust-lang/rust/issues/22020
[scoped-attributes]: https://github.com/rust-lang/rfcs/blob/master/text/0560-integer-overflow.md#scoped-attributes-to-control-runtime-checking
[compile time and runtime]: …
> registry: fix panic 'attempt to add with overflow'

- Cargo.toml
- src/desc.rs
- src/lib.rs
This allows dropping the dependency on regex, making the instrumentation
library much more lightweight.
This also fixes a bug with metric name validation, where an initial
colon was incorrectly disallowed. See data model for correct format:
https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
This may be because the library closely follows the official Go library,
which also had this issue.
Refs #85
Refs https://github.com/prometheus/client_golang/pull/255
> desc: Replace regex name validation with functions

- .travis.yml
- Cargo.toml
- Makefile
- examples/example_push.rs
- src/lib.rs
This PR introduces a new feature `push`.  It allows building core instrumentation library without hyper and libc.
~~There are a few API changes:~~
- ~~mod `push` is published.~~
- ~~following functions are moved to mod `push`.~~
```
push_metrics
push_add_metrics
push_collector
push_add_collector
hostname_grouping_key
```
Close #84 
PTAL @siddontang @kamalmarhubi
> *: add feature "push"

- examples/example_hyper.rs
- examples/example_push.rs
- src/macros.rs
Macro API changes:
* `register_(counter|gauge)`
* Reomved:
- `( $ NAME : expr , $ HELP : expr $ ( , $ CONST_LABELS : expr ) * )`
* `register_(counter_vec|gauge_vec)`
* Reomved
- `( $ NAME : expr , $ HELP : expr , $ CONST_LABELS : expr , $ LABELS_NAMES : expr )`
* `histogram_opts!`
* Remove: 
- `histogram_opts!( $ NAME : expr , $ HELP : expr , [ $ ( $ BUCKETS : expr ) , * ] )`
- `histogram_opts!( $ NAME : expr , $ HELP : expr $ ( , $ CONST_LABELS : expr ) * )`
- `histogram_opts!( $ NAME : expr , $ HELP : expr , $ CONST_LABELS : expr , [ $ ( $ BUCKETS : expr ) , + ] )`
* Add:
- ~~`histogram_opts!( $ OPTS : expr , $ BUCKETS : expr )`~~
- `histogram_opts!( $ NAME : expr , $ HELP : expr )`
- `histogram_opts!( $ NAME : expr , $ HELP : expr , $ BUCKETS : expr )`
- `histogram_opts!( $ NAME : expr …
> Refactor macros

- benches/histogram.rs
- src/desc.rs
- src/histogram.rs
If we use metrics frequently, it may reduce the performance. For Counter and Gauge, we can simply use a int value in local and then flush to metric in batch, but it is not easy for histogram.
So we support LocalHistogram, it can be only used in single thread, and you must call `flush` interval to flush to metric. 
Benchmark 
```
test histogram::bench_histogram_local                   ... bench:           8 ns/iter (+/- 2)
test histogram::bench_histogram_local_timer             ... bench:          60 ns/iter (+/- 2)
test histogram::bench_histogram_no_labels               ... bench:          89 ns/iter (+/- 4)
test histogram::bench_histogram_timer                   ... bench:         151 ns/iter (+/- 10)
test histogram::bench_histogram_with_label_values       ... bench:         154 ns/iter …
```
> support local histogram

- .travis.yml
- Cargo.toml
- Makefile
- examples/example_process_collector.rs
- src/lib.rs
- src/process_collector.rs
- src/registry.rs
Process collector which exports the current state of process metrics including cpu, memory and file descriptor usage as well as the process start time for the given process id.
For now, process collector only supports **Linux** platform.
PTAL @siddontang @disksing @BusyJay 
Close #65
> Process collector

- src/process_collector.rs
- src/registry.rs
This fixes `undefined reference to 'prlimit'` on CentOS 6.8 glibc 2.12.
PTAL  @iamxy @siddontang @BusyJay
> process_collector: get max fd from /proc/[pid]/limits

- src/process_collector.rs
Actual limits has tailing whitespace, which rustfmt warns, this PR remove those, since they are not correctness-related.  
https://github.com/rust-lang-nursery/rustfmt/issues/1220
> process: remove tailing whitespace and improve performance

- Cargo.toml
- benches/histogram.rs
- src/histogram.rs
- src/lib.rs
Coarse timer uses [`CLOCK_MONOTONIC_COARSE`](https://linux.die.net/man/2/clock_gettime), it is faster but less precise, and linux only.
Benchmark
```
test histogram::bench_histogram_coarse_timer            ... bench:          48 ns/iter (+/- 0)
test histogram::bench_histogram_timer                   ... bench:          86 ns/iter (+/- 0)
test histogram::bench_local_histogram_coarse_timer      ... bench:          48 ns/iter (+/- 0)
test histogram::bench_local_histogram_timer             ... bench:          85 ns/iter (+/- 0)
```
> histogram: add a fast coarse timer

- src/histogram.rs
The processors in an SMP system do not start all at exactly the same time
and therefore the timer registers are typically running at an offset.
Use millisecond resolution for ignoring the error.
CC pingcap/tikv#2165
> histgram: use millisecond resolution for coarse timer

- src/lib.rs
[The existing docs for CounterVec](https://docs.rs/prometheus/0.3.1/prometheus/type.CounterVec.html) (and GaugeVec/HistogramVec) don't show that `fn new(...)` exists, and `MetricVec` isn't clickable, so you can't tell what methods exist (but you can still call them if you already know what they are).
This exports MetricVec publicly, so things show up in the docs correctly.
> Add public export for MetricVec

- .travis.yml
Remove unnecessary ci jobs. As for 32-bit rust, rust-prometheus only supports stable channel.
> travis: reduce CI jobs

- src/registry.rs
This PR replaces `std::sync::Rwlock` with `spin::RwLock`, and removes annoying `unwrap()`.
CC #115
> registry: use spin lock

- benches/benches.rs
- benches/counter.rs
- benches/gauge.rs
- benches/histogram.rs
- examples/example_embed.rs
- examples/example_hyper.rs
- examples/example_process_collector.rs
- examples/example_push.rs
- src/atomic64.rs
- src/desc.rs
- src/encoder/mod.rs
- src/encoder/pb.rs
- src/encoder/text.rs
- src/errors.rs
- src/gauge.rs
- src/histogram.rs
- src/lib.rs
- src/local.rs
- src/metrics.rs
- src/process_collector.rs
- src/push.rs
- src/registry.rs
- src/value.rs
- src/vec.rs
TiKV has updated to rustfmt-nightly 0.3.4. We need to track this version.
> Use rustfmt 0.3.4 to format the code

- .travis.yml
This PR adds an allow-failed build job and enables clippy lint on the job only. Now, annoy compile errors will not fail the whole ci.
> Ignore clippy build failure

- Cargo.toml
- src/counter.rs
`LocalCounter` should not export `new`, it can only be derived from a `Counter`.
> counter: private LocalCounter::new

- Cargo.toml
- src/registry.rs
Gather should prune emptied MetricFamily.
```
// normalizeMetricFamilies returns a MetricFamily slice with empty
// MetricFamilies pruned and the remaining MetricFamilies sorted by name within
// the slice, with the contained Metrics sorted within each MetricFamily.
func normalizeMetricFamilies(metricFamiliesByName map[string]*dto.MetricFamily) []*dto.MetricFamily {
for _, mf := range metricFamiliesByName {
sort.Sort(metricSorter(mf.Metric))
}
names := make([]string, 0, len(metricFamiliesByName))
for name, mf := range metricFamiliesByName {
if len(mf.Metric) > 0 {
names = append(names, name)
}
}
sort.Strings(names)
result := make([]*dto.MetricFamily, 0, len(names))
for _, name := range names {
result = append(result, metricFamiliesByName[name])
}
return result
}
``` …
> registry: do not gather emptied MetricFamily

- examples/example_embed.rs
- examples/example_hyper.rs
- examples/example_int_metrics.rs
- examples/example_process_collector.rs
- examples/example_push.rs
- rustfmt.toml
- src/atomic64/fallback.rs
- src/atomic64/mod.rs
- src/atomic64/nightly.rs
- src/counter.rs
- src/desc.rs
- src/encoder/mod.rs
- src/encoder/pb.rs
- src/encoder/text.rs
- src/errors.rs
- src/gauge.rs
- src/histogram.rs
- src/lib.rs
- src/macros.rs
- src/metrics.rs
- src/process_collector.rs
- src/push.rs
- src/registry.rs
- src/value.rs
- src/vec.rs
Pinning rustfmt to the version that TiKV is using currently.
Also re-arranged `use` statements to be grouped follows this order:
1. std
2. 3rd-party modules
3. super or internal modules
> Reformat using a more recent version of rustfmt

- Cargo.toml
> Fix protobuf dependency, as 1.4.1 makes builds fail.

- CHANGELOG.md
- Cargo.toml
- README.md
- static-metric/Cargo.toml
We have introduced some changes recently, for example, updating the protobuf version. This PR bumps the version for publishing.
> Bump versions

- static-metric/Cargo.toml
- static-metric/examples/advanced.rs
- static-metric/examples/metric_enum.rs
- static-metric/src/builder.rs
- static-metric/src/parser.rs
- static-metric/tests/label_enum.rs
- static-metric/tests/metric.rs
When applying compile-time-unknown static metrics, currently we follow this style:
```rust
// Suppose we have `let label = "post"` elsewhere.
SOME_STATIC_VEC_METRIC.get(label).unwrap().inc();
```
As an equivalent to:
```rust
SOME_STATIC_VEC_METRIC.post.inc();
```
Since the value of `label` is unknown in compile time, we have to match it into the actual field at runtime, by using `.get(label).unwrap()`.
According to benchmark, this does not introduce notable overheads, which is good. However this cannot ensure safety: what if `label`'s value is not valid? This will lead to `unwrap()` panic.
From existing applications, we found out that in fact in most of the time we can make it safe in the compile time! We can simply assign an `enum` type for it.
For `label_enum` definitions, we expand it …
> Make compile-time-unknown static metrics type safe

- .travis.yml
Also see: https://internals.rust-lang.org/t/clippy-is-available-as-a-rustup-component/7967
Move the clippy we use from being installed by `cargo` to being installed by `rustup`. If you find strange problems with clippy after they are merged you will need to do: `cargo uninstall clippy && cargo uninstall clippy-lints && rustup self update`
This is because the old versions of rustup don't know that clippy is managed, so they give errors like `subcommand clippy does not exist`.
Currently the clippy version must be managed separate from the Rust nightly. Using Rustup will allow each of our projects to depend on their own clippy versions and help avoid some toolchain related problems.
* https://github.com/pingcap/raft-rs/pull/95
* https://github.com/pingcap/rust-prometheus/pull/186
* …
> Use rustup provided clippy.

- CHANGELOG.md
- Cargo.toml
- examples/example_push.rs
- src/lib.rs
- src/push.rs
Looking at prometheus libraries in other languages, most seem to support `Basic Auth` & `TLS` when using `push` mode for pushing metrics to pushgateway. So adding support for both here as well.
Note:
- using `reqwest` instead of updating `hyper` to latest versions, which seemed simpler (`reqwest` api is also  really similar to `hyper`'s api from version 0.9)
- `reqwest` requires `openssl` on [linux](https://github.com/seanmonstar/reqwest#requirements) (as does `hyper-tls`)
Let me know if this seems useful & I will polish up the PR.
> TLS & Basic Auth support to push mode

- src/counter.rs
- src/value.rs
I wanted to put counters in a struct that needs to have a `Debug`, so it's easiest if the counters have it too.
> Implement Debug on GenericCounter

- src/registry.rs
`unregister` should remove desc from desc_ids
https://github.com/prometheus/client_golang/blob/5b23715facdef1452016bae512489c3cdf82458c/prometheus/registry.go#L372-L374
> registry: allow re-registration

- src/histogram.rs
`HistogramTimers` should be either kept in a variable (so that it will not be immediately dropped), or manually call its `observe_duration()` interface. In this way, it should be marked as `#[must_use]`.
Resolve #145
> HistogramTimers should be #[must_use]

- src/atomic64/fallback.rs
- src/atomic64/mod.rs
- src/encoder/pb.rs
- src/encoder/text.rs
- src/errors.rs
- src/histogram.rs
- src/lib.rs
- src/metrics.rs
- src/vec.rs
- static-metric/src/lib.rs
Deny missing docs on `prometheus`. Didn't do it to `prometheus-static` since it has many non-user facing things.
> Deny missing docs

- src/lib.rs
This fixes a clippy hard-failure due to a renamed lint:
```
error: lint `clippy::new_without_default_derive` has been renamed to `clippy::new_without_default`
```
> clippy: fix renamed lint

- examples/example_custom_registry.rs
- src/lib.rs
- src/registry.rs
This adds a getter to expose the default/static registry. It also includes an example showing how to use multiple and custom registries, and how to perform registration across function boundaries.
Closes: https://github.com/pingcap/rust-prometheus/issues/230
> prometheus: expose the default registry

- examples/example_custom_registry.rs
- src/registry.rs
This adds an additional constructor to provide common namespace/labels
for a registry, to be used for all collected metrics.
Closes: https://github.com/pingcap/rust-prometheus/issues/228
> registry: add optional common prefix and labels

- .travis.yml
- src/plain_model.rs
- src/registry.rs
Compilation of the latest version (0.6.0) failed in one of my projects with the following error:
```
error[E0599]: no method named `take_label` found for type `&mut proto::Metric` in the current scope
--> src/registry.rs:208:49
|
208 |                         let mut labels = metric.take_label().into_vec();
|                                                 ^^^^^^^^^^
error: aborting due to previous error
```
Upon investigation, I found out this happened if the crate was configured not to use the protobuf feature (e.g. with `default-features = false` when listed as a dependency, or with `cargo build --no-default-features`).
Further investigation revealed that the `Metric` implementation in `plain_model.rs` was missing the `mut_label` and `take_label` methods, which exist in the version …
> Fix compilation without protobuf

- src/counter.rs
This fixes `should_panic` tests in release mode, as they rely on
debug assertions.
> counter: fix tests in release mode

- CHANGELOG.md
- Cargo.toml
- README.md
- src/counter.rs
When local metrics are used in thread local environments, it would be better to provide immutable interfaces, so that there is no need to wrap local metrics with a `RefCell`.
`LocalHistogram` is already immutable, so this PR makes `Local(Int)Counter` immutable.
> Provide immutable interface for local counter

- static-metric/Cargo.toml
- static-metric/Makefile
- static-metric/examples/local.rs
- static-metric/src/builder.rs
- static-metric/tests/label_enum.rs
rust-prometheus 0.7 provides immutable local counter, so that the macro can be simplified.
> Utilize prometheus 0.7 features

- src/push.rs
This updates trait objects to use the explicit `dyn Collector`
syntax, fixing build failures due to deprecations on beta and
nigthly toolchains.
Closes: https://github.com/pingcap/rust-prometheus/issues/258
> push: use explicit syntax for trait objects

- src/atomic64.rs
- src/counter.rs
- src/gauge.rs
- src/histogram.rs
- src/lib.rs
- src/process_collector.rs
- src/push.rs
- src/registry.rs
- src/vec.rs
This implements Debug on all public types that were missing it,
and adds a lint to force future types to implement it.
> lib: deny missing Debug implementations

- Cargo.toml
Use a 2017 dependency instead of a 2016 dependency. :-P
This simplifies the build graph for projects using a modern procinfo like TiKV.
> Cargo.toml: Update procinfo

- src/macros.rs
This small PR allows for trailing commas to be omitted when using the `labels!` macro. It also tidies up the logic a little bit.
> Allow omitting trailing commas in labels macro

- Cargo.toml
A vulnerability was fixed in spin and is reported by cargo-audit. Although exploitation sounds unlikely, the warning shows up transitively for packages that depend on rust-prometheus, so updating it would be nice.
https://rustsec.org/advisories/RUSTSEC-2019-0013.html
> Update spin dependency to 0.5.2

- .travis.yml
- src/histogram.rs
LocalHistogramTimer::new_coarse() should take a local histogram as an
arg.
> Fix compile on nightly.

- examples/example_edition_2018.rs
- src/macros.rs
when using this crate on a rust 2018 project, some macros like `register_counter_vec` will fail with a very confusing error - that's because you need to bring the helper `__register_counter_vec` into scope.
with this change this rust 2018 style code works just fine:
```
fn main() {
prometheus::register_counter!("test_macro_2", "help");
prometheus::register_counter_vec!("errorz", "errors", &["error"]).unwrap();
prometheus::register_gauge!("test_macro_gauge_2", "help");
prometheus::register_gauge_vec!("test_macro_gauge_vec_3", "help", &["a", "b"]);
prometheus::register_histogram!("test_macro_histogram_4", "help", vec![1.0, 2.0]);
prometheus::register_histogram_vec!(
"test_macro_histogram_4",
"help",
&["a", "b"],
vec![1.0, 2.0]
);
prometheus::register_int_counter!("meh", "foo"); …
```
> export local inner macros for rust2018 use

- src/histogram.rs
The logic behind linear buckets is prone to accumulate error.
This tweaks the implementation to avoid that. It multiplies
by integer step for each iteration, resulting in better behaved
buckets.
Ref: https://github.com/pingcap/rust-prometheus/pull/266
Co-Developed-by: Simonas Kazlauskas <git@kazlauskas.me>
Signed-off-by: Luca Bruno <luca.bruno@coreos.com>
> histogram: avoid accumulating error in linear buckets

- src/histogram.rs
add public accessor for histogram so that monitored server can access history data on local end.
Signed-off-by: tabokie <xy.tao@outlook.com>
> Add accessor for histogram

- static-metric/Cargo.toml
I think it's time to update `syn`, `quote` and `proc-macro2` to v1.0.
`syn`, `quote` and `proc-macro2` in the upstream dependency of `rust-prometheus` have been upgraded to version 1.0.
> Update syn, quote, proc-macro2 to v1.0

- Cargo.toml
- src/process_collector.rs
This commit doesn't add any new features, but allows future commits to
use features in procfs that are missing from procinfo.  Also hopefully rust-prometheus won't have to maintain as much code to deal with process info.
The idea for this change came from @brndnmtthws, who wanted to use some features in procfs that are missing from procinfo.  I haven't added these features yet, but if this PR is accepted, I can help with that work too.   Disclaimer: I am the author of the procfs crate.
Closes #272
> Switch from procinfo to procfs

- CHANGELOG.md
- README.md
This PR modifies necessary documentation to use the verson 0.8.0. We will use this commit to publish the version.
Note that `Cargo.toml` was already changed to 0.8.0.
Signed-off-by: Breezewish <me@breeswish.org>
> Bump version to 0.8.0

- src/atomic64.rs
- src/counter.rs
- src/desc.rs
- src/encoder/pb.rs
- src/encoder/text.rs
- src/errors.rs
- src/gauge.rs
- src/histogram.rs
- src/macros.rs
- src/metrics.rs
- src/registry.rs
- src/value.rs
- src/vec.rs
Wherever possible, use the default linking style of looking names up in the
enclosing namespace without adding an explicit link, but sometimes we need to
add the link target via parens, in those cases correct from `::Name` to
`crate::Name`.
> Correct intra-doc links

- static-metric/proc-macros/src/builder.rs
Signed-off-by: Renkai <gaelookair@gmail.com>
To make a label enum possible to be a HashMap key
> add derive for label enum

- CHANGELOG.md
- src/encoder/text.rs
This adds code for handling summary metrics when calling the "encode" function to write quantile, count and sum metrics using the functions implemented on `Summary`.
> Add summary metric type to the encode function

- Cargo.toml
- src/auto_flush.rs
- src/registry.rs
- src/vec.rs
Benchmarks:
```
name                                              spin ns/iter  parking_lot ns/iter  diff ns/iter   diff %  speedup 
bench_atomic_f64                                  4             4                               0    0.00%   x 1.00 
bench_atomic_i64                                  4             4                               0    0.00%   x 1.00 
bench_counter_no_labels                           4             4                               0    0.00%   x 1.00 
bench_counter_no_labels_concurrent_nop            4             4                               0    0.00%   x 1.00 
bench_counter_no_labels_concurrent_write          43            128                            85  197.67%   x 0.34 
bench_counter_with_label_values                   35            36 …
```
> Replace spin with parking_lot

- src/counter.rs
- src/gauge.rs
- src/histogram.rs
- src/metrics.rs
Otherwise you force same type on both arguments which is not ideal
> Use different generic parameters where needed

- proto/proto_model.rs
- src/lib.rs
Currently all CI builds are failing due to Rust fmt trying to format `proto/proto_model.rs`.
For now this patch simply formats the given file.
In the future I would suggest:
1. Have rustfmt ignore `proto/` via the (not yet stable) `ignore` attribute in `rustfmt.toml`.
2. Generate `proto/proto_model.rs` on each CI run to ensure the checked-in version matches and is up-to-date.
> proto/proto_model: Run rust fmt

- src/histogram.rs
- src/value.rs
`make_label_pairs` expects `desc.variable_labels.len()` to equal the provided
`label_values.len()`. Instead of panicing on out of range indexing
return an error.
Fixes https://github.com/tikv/rust-prometheus/issues/306.
> src/value: Have make_label_pairs error instead of panic

- Cargo.toml
- benches/text_encoder.rs
- src/encoder/text.rs
This pull request addresses the low-hanging-fruits within `src/encoder/text.rs` with the following commits:
- src/benches&src/bin: Add basic text encoder benchmark
- src/encoder/text: Use `write_all` instead of `write_fmt`
Instead of going through `write!` which calls `write_fmt` use `write_all` directly skipping the additional formatting overhead.
- src/encoder/text: Use regex crate to determine if escaping is needed
Within `escape_string` instead of always allocating a new String and iterating through each character one-by-one, first check whether the input string needs any escaping, if not, return without any allocation. If it does need escaping, start from the first occurence.
Benchmark results on a `Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz`:
```bash
$ cargo benchcmp master optimized …
```
> src/encoder/text: Optimize metric formatting

- README.md
- src/lib.rs
- Move all documentation to src/lib linking to it within README (to ensure there is no mismatch)
- Fix build status link.
- Update crate feature documentation.
---
Replaces https://github.com/tikv/rust-prometheus/pull/330.
> *: Rework README and src/lib documentation

- src/registry.rs
Currently, `register` returns `Error::Msg` if a collector is registered
more than once. This commit updates the returned error to match the
function documentation.
Fixes #247
> Return `Error::AlreadyReg` on duplicate collector

- benches/histogram.rs
- src/atomic64.rs
- src/histogram.rs
A histogram supports two main execution paths:
1. `observe` which increases the overall observation counter, updates the observation sum and increases a single bucket counter.
2. `collect` which snapshots the state of the histogram and exposes it as a Protobuf struct.
If an observe and a collect operation interleave, the latter could be exposing a snapshot of the histogram that does not uphold all histogram invariants. For example for the invariant that the overall observation counter should equal the sum of all bucket counters: Say that an `observe` increases the overall counter but before updating a specific bucket counter a `collect` operation snapshots the histogram.
The above race condition has been solved in the Golang Prometheus client with …
> src/histogram: Make Histogram::observe atomic across collects

- static-metric/Cargo.toml
- static-metric/examples/register_integration.rs
- static-metric/proc-macros/Cargo.toml
- static-metric/proc-macros/src/lib.rs
- static-metric/src/lib.rs
As of Rust 1.45,  `proc-macro-hack` is superseded by native support for #[proc_macro] in expression position.
> Remove proc-macro-hack

- CHANGELOG.md
- Cargo.toml
- static-metric/Cargo.toml
Following the basic release approach suggested in https://github.com/tikv/rust-prometheus/issues/305#issuecomment-654729638 to create a release candidate (`0.10.0-rc.1`).
Once this is merged I would:
1. Create and push a git tag.
```bash
tag="v$(sed -En 's/^version = \"(.*)\"$/\1/p' Cargo.toml)"
git tag -s "${tag}" -m "${tag}"
git push libp2p --tags --dry-run
git push libp2p --tags
```
2. Publish to crates.io.
```
cargo clean
git clean -fd
cargo publish --dry-run
cargo publish
```
I am still not against the more advanced release process for future releases suggested by @lucab in https://github.com/tikv/rust-prometheus/issues/305#issuecomment-658083355.
> *: Prepare release candidate 0.10.0-rc.1

- CHANGELOG.md
- Cargo.toml
- static-metric/Cargo.toml
Follow up to release candidate https://github.com/tikv/rust-prometheus/pull/340.
We (Parity) have been running `v0.10.0-rc.1` on two Kusama (testnetwork) nodes since last week Thursday (27th). I have not seen any abnormal behavior on either of the two. (Ref: https://github.com/paritytech/substrate/pull/6964)
With the above in mind I am suggesting to promote the release candidate to the `v0.10.0` release. Any objections?
> *: Prepare release 0.10.0

- README.md
Changelog:
- Update wording in **feature** section to indicate that there are crate features which need to be enabled before they can be used
- Run markdownlint on README
- Add link for word **push metrics** to show what the push metrics support actually is
Reason:
Reduce confusion as to if the feature section talks about library features or crate features.
Fixes #345
> Update "features" section in README

- .github/dependabot.yml
>  Dependabot creates pull requests to keep your dependencies secure and
up-to-date.
See https://dependabot.com/ for details.
I have had a great experience with dependabot both on my personal projects as well as [rust-libp2p](https://github.com/libp2p/rust-libp2p/pull/1744) thus far.
Discussed in https://github.com/tikv/rust-prometheus/issues/319.
> .github/: Add dependabot.yml

- benches/desc.rs
- src/desc.rs
Current CI runs fail (see https://github.com/tikv/rust-prometheus/pull/353) due to the following Clippy warning:
```
error: match expression looks like `matches!` macro
--> src/desc.rs:19:16
|
19 |               && match c as u8 {
|  ________________^
20 | |                 b'a'..=b'z' | b'A'..=b'Z' | b'_' | b':' => true,
21 | |                 _ => false,
22 | |             }
| |_____________^ help: try this: `matches!(c as u8, b'a'..=b'z' | b'A'..=b'Z' | b'_' | b':')`
|
= note: `-D clippy::match-like-matches-macro` implied by `-D clippy`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#match_like_matches_macro
```
Instead of using `matches!` I propose to remove the entire manual validation in favor of a simple regex.
For those worried about …
> src/desc: Validate metric and label names via regex crate

- static-metric/CHANGELOG.md
- static-metric/src/parser.rs
- static-metric/tests/metric.rs
When determining whether to parse a struct or an enum the `Parse`
implementation for `StaticMetricMacroBodyItem` checks for the tokens
`struct` or `enum`. Given that the two can optionally be preceeded by
a visibility token (e.g. `pub(crate)`) one needs to peek at both the
first and the second token.
Follow up on https://github.com/tikv/rust-prometheus/pull/268/.
> static-metric/src/parser: Allow not specifying visibility

- static-metric/benches/benches.rs
> `fn get()` is only available when label is defined by `label_enum`.
> static-metric/benches: Use label_enum and get

- .travis.yml
Run benchmarks on each pull request to ensure they compile and won't panic. 
In the long run we might want to remove the line below fixing the nightly version instead.
```yaml
allow_failures:
- rust: nightly
```
Signed-off-by: Max Inden <mail@max-inden.de>
> .travis.yml: Run benchmarks on each run

- examples/example_hyper.rs
- src/vec.rs
- static-metric/README.md
- static-metric/examples/advanced.rs
- static-metric/examples/local.rs
- static-metric/examples/make_auto_flush_static_counter.rs
- static-metric/examples/make_auto_flush_static_metric_histogram.rs
- static-metric/examples/register_integration.rs
- static-metric/examples/with_lazy_static.rs
By convention unit-less Prometheus counters are postfixed with `_total`.
See https://prometheus.io/docs/practices/naming/ for details.
> *: Follow metric naming convention for unit-less count

- .github/workflows/rust.yml
- .travis.yml
- Cargo.toml
- benches/atomic.rs
- benches/counter.rs
- benches/desc.rs
- benches/gauge.rs
- benches/histogram.rs
- benches/text_encoder.rs
- static-metric/Cargo.toml
- static-metric/benches/benches.rs
This moves all benches to criterion-rs, in order to allow running
benchmarks on a stable toolchain.
This also moves benchmarking and linting jobs to a pinned toolchain,
under GitHub actions.
> benches: move to criterion-rs and GitHub actions

- src/counter.rs
According to the definition of Prometheus's [Counter type](https://prometheus.io/docs/concepts/metric_types/#counter), the `AtomicU64` is preferred to `AtomicI64` for `IntCounter*` types:
> A counter is a cumulative metric that represents a single monotonically increasing counter whose value can only increase or be reset to zero on restart. 
Fix #364 .
> Change Integer Counter type from AtomicI64 to AtomicU64

- src/process_collector.rs
Picking up https://github.com/eminence/procfs/pull/105.
For a service with 80k open file descriptors this reduces metric collection time from 500ms down to 100ms (no contention).
> Switch to more efficient fd_count() for process_open_fds

- CHANGELOG.md
- Cargo.toml
- static-metric/Cargo.toml
As you can see by CHANGELOG.md the list of changes is not long. Still to keep the release cycle short I am proposing to release `prometheus` `v0.11.0`.
Once this is released I can as well cut `prometheus-static-metric` `v0.5.0`.
What do you think?
> *: Prepare prometheus v0.11.0 release

- static-metric/CHANGELOG.md
- static-metric/Cargo.toml
Follow up for https://github.com/tikv/rust-prometheus/pull/370 cutting a new release of `prometheus-static-metric` as well.
Signed-off-by: Max Inden <mail@max-inden.de>
> static-metric: Prepare release v0.5.0

- .github/workflows/rust.yml
- static-metric/Cargo.toml
Releasing static-metric fails with:
```
Caused by:
failed to parse manifest at
`/xxx/tikv/rust-prometheus/target/package/prometheus-static-metric-0.5.0/Cargo.toml`
Caused by:
can't find `benches` bench, specify bench.path
```
This is due to the `benches` folder not being included in the final
release tarball. With this commit the folder is included and thus
releasing prometheus-static-metric would succeed.
Off the top of my head this is the right way to go. Open for alternative
suggestions.
> static-metric/Cargo.toml: Remove include section

- src/atomic64.rs
- src/histogram.rs
- src/timer.rs
- static-metric/src/auto_flush_from.rs
- static-metric/src/lib.rs
`compare_and_swap` is deprecated in favor of `compare_exchange` and
`compare_exchange_weak`. This commit replaces the former with either of
the two latter options.
Also see [migration guide](https://doc.rust-lang.org/beta/std/sync/atomic/struct.AtomicU64.html#migrating-to-compare_exchange-and-compare_exchange_weak).
I welcome anyone to review this change. Given that this is a rather subtle change (especially with memory ordering) possibly resulting in a much greater disaster, please don't merge this just yet. I would like to review this myself once more with a fresh mind.
`
> src/: Replace deprecated compare_and_swap with compare_exchange(_weak)

- static-metric/CHANGELOG.md
- static-metric/Cargo.toml
I would like to cut `static-metric` `v0.5.1` so others can make use of the fix for https://github.com/tikv/rust-prometheus/issues/378.
//CC @fggarcia
> static-metric: Prepare release v0.5.1

- Cargo.toml
- src/desc.rs
- src/encoder/text.rs
`regex` was used only in four trivial cases that could be implemented
more simply, either naively or using memchr, without losing performance.
As such the dependency needlessly increases build time, size of binary
and attack surface.
This change makes `regex` optional and defaults to `naive`/`memchr`
implementations. This *improves* performance a bit. The dependency
could've been removed entirely but was kept in case regression is
discovered on another platform and to make comparing the performance
easier. It can be removed in the future if the code is proven to be
reliable.
Benchmarked on x86_64. Thumbs up for providing convenient benches. :)
> Make regex dependency optional

- src/desc.rs
This fixes a compile error on current beta toolchain, which started
enforcing that panic messages must be string literals (with format
specifiers).
> desc: fix format string for panic

- CHANGELOG.md
- Cargo.toml
- static-metric/Cargo.toml
- Improvement: Fix format string in panic!() calls (#391)
- Improvement: Replace regex with memchr (#385)
- Improvement: Update reqwest requirement from ^0.10 to ^0.11 (#379)
Closes: https://github.com/tikv/rust-prometheus/issues/394
> prometheus: release 0.12.0

- examples/example_custom_registry.rs
- examples/example_hyper.rs
- examples/example_int_metrics.rs
- examples/example_push.rs
- src/lib.rs
- src/macros.rs
- src/process_collector.rs
- src/push.rs
- src/registry.rs
- src/timer.rs
- static-metric/Cargo.toml
- static-metric/Makefile
- static-metric/README.md
- static-metric/benches/benches.rs
- static-metric/examples/advanced.rs
- static-metric/examples/local.rs
- static-metric/examples/make_auto_flush_static_counter.rs
- static-metric/examples/make_auto_flush_static_metric_histogram.rs
- static-metric/examples/metric_enum.rs
- static-metric/examples/register_integration.rs
- static-metric/examples/simple.rs
- static-metric/examples/with_lazy_static.rs
- static-metric/src/auto_flush_builder.rs
- static-metric/src/auto_flush_from.rs
- static-metric/src/builder.rs
- static-metric/src/lib.rs
- static-metric/src/register_macro.rs
- static-metric/tests/label_enum.rs
- static-metric/tests/metric.rs
Signed-off-by: JmPotato <ghzpotato@gmail.com>
`macro_use` and `extern crate` are no longer needed in 99% of circumstances. So I clean up them to make sure it's more consistent, more flexible, and easier to look up the macro definition. You can check [Path clarity](https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html) for more detials.
> Clean up the use of macro_use and extern crate

- src/encoder/text.rs
I saw that we do
```rust
let mut buffer = vec![];
let encoder = TextEncoder::new();
encoder.encode(&prometheus::gather(), &mut buffer).unwrap();
String::from_utf8(buffer).unwrap()
```
a bunch of times in [near](github.com/near/nearcore) and figured that the library can probably guaranty utf8 validity and remove the need for one unwrap here. 
This turned out to be slightly more involved then I've thought, as there's no standard way to explain that you'll only write utf8 to a `Write`, but it wasn't to hard either. 
As a bonus, `TextEncoder` impl now is statically guaranteed to produce only valid utf8
> Add convenience TextEncoder functions to encode directly to string

- src/histogram.rs
To prevent timers from panicking when observed, this PR modifies the `HistogramTimer` to use saturating arithmetic.
The docs for [`std::time::Instant::elapsed`](https://doc.rust-lang.org/std/time/struct.Instant.html#method.elapsed) note that it can panic if clock monotonicity is violated. Further, the source for `Instant::now` notes that buggy clocks on various platforms have caused issues:
https://github.com/rust-lang/rust/blob/fe1c942eee3489743d655d81ca89166217db0547/library/std/src/time.rs#L223-L250
I recently observed a panic caused by a monotonicity violation in a virtualised environment. There's a full backtrace available here: https://github.com/sigp/lighthouse/issues/2485
The alternative to saturating arithmetic would be to use checked arithmetic and avoid updating the histogram …
> Avoid panics from `Instant::elapsed`

- src/process_collector.rs
This simply retrieves and exports the value of the `num_threads` field from the
already populated `procfs::process::Stat` that CPU, memory and start time are
sourced.
> Export thread count from `process_collector`

- src/macros.rs
This adds macros for static instantiation of collectors using a custom registry.
Addresses #386
> feat(macros): add macros for collectors with custom registry

- CHANGELOG.md
- Cargo.toml
- Bug fix: Avoid panics from `Instant::elapsed` (#406)
- Improvement: Allow trailing comma on macros (#390)
- Improvement: Add macros for custom registry (#396)
- Improvement: Export thread count from `process_collector` (#401)
- Improvement: Add convenience TextEncoder functions to encode directly to string (#402)
- Internal change: Clean up the use of macro_use and extern crate (#398)
- Internal change: Update dependencies
Closes: https://github.com/tikv/rust-prometheus/issues/414
> prometheus: release 0.13.0

- src/encoder/text.rs
This fixes the only clippy warning.
> clippy: Remove needless borrow.

- src/auto_flush.rs
- src/macros.rs
This fixes broken doc links by specifically telling it where to find the linked entity.
> Fix broken doc links.

- src/registry.rs
The change is inconsequential, just something I noticed while reading the code.
> Derive default instead of obvious manual impl

- src/encoder/mod.rs
This is to address issue #432 .
> encoder: fix docs

- CHANGELOG.md
- Cargo.toml
- Improvement: ProcessCollector use IntGauge to provide better performance (#430)
- Bug fix: Fix re-export of TEXT_FORMAT to not require protobuf (#416)
- Bug fix: Fix doc for encode (#433)
- Bug fix: Fix broken doc links (#426)
- Bug fix: Fix crates.io badge (#436)
- Internal change: Derive default instead of obvious manual impl (#437)
- Internal change: Remove needless borrow (#427)
- Internal change: Update dependencies
Closes: https://github.com/tikv/rust-prometheus/issues/439
> prometheus: release 0.13.1

- src/process_collector.rs
The crate didn't compile on 32-bit targets any more due to `libc::sysconf()` returning a 32-bit value on those targets.
Fixes #442
> process_collector: fix compilation on 32-bit targets

- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.toml
- src/desc.rs
- src/histogram.rs
- static-metric/src/auto_flush_builder.rs
- static-metric/src/parser.rs
- Bug fix: Fix compilation on 32-bit targets (#446)
> prometheus: release 0.13.2

- CHANGELOG.md
- Cargo.toml
- Bug fix: Prevent ProcessCollector underflow with CPU time counter (#465)
- Internal change: Update dependencies
> prometheus: release 0.13.3

- .github/workflows/rust.yml
This adds a new CI job to verify building with a minimum supported Rust version (MSRV), currently set at 1.57.0.
This is done in preparation for a future edition-2021 switch.
> ci: add a job for minimum toolchain (MSRV)

- src/lib.rs
- src/pulling_gauge.rs
First of all, thank you for this crate! We've been using it in production for a bit and are super happy.
As part of this, we've written a few additional metric types that allow us to instrument our app in an easier fashion. This PR attempts to merge the first of these back to the upstream project. If there is interest, then we'd be happy to send more PRs with other helper types (i.e. we have a MaximumOverIntervalGauge that allows monitoring of quickly changing values).
The metric type that this PR is adding is the **PullingGauge**. It is useful in scenarios where we want to expose a particular value but it is infeasible to keep the metric up to date all of the time (i.e. it changes a lot in hot code paths). The most common example for us internally is to expose the size of a _Vector_ or …
> Add PullingGauge gauge type

- .github/workflows/rust.yml
- src/pulling_gauge.rs
After merging #405 the `master` [fails](https://github.com/instrumentisto/metrics-prometheus-rs/actions/runs/3751488097/jobs/6372528212#step:4:80) to build [with `--no-default-features`](https://github.com/instrumentisto/metrics-prometheus-rs/pull/3/commits/f928edd4975a7d7b8acd24029aa532462e466bfb#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R23). The regression wasn't caught by CI as it doesn't check this scenario.
- Fix the compilation issue by using `crate::from_vec!()` in `PullingGauge` implementation (as the other metric types do).
- Add commands to check `--no-default-features` scenario on CI.
> pulling_gauge: fix build with --no-default-features

- .github/workflows/rust.yml
The toolchain is now installed with [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain).
> ci: replace unmaintained/outdated github actions

- Cargo.toml
- README.md
The support for using Travis was started in 200c362e5e58442230334d6126817fcceed47c25 and finished in bb90a19e6db8551d9a08c640f403e5ada20a49f6.
> ci: Update badge info to not refer to Travis CI.

- .github/workflows/rust.yml
The main thing here is an update on the GitHub side for what version of Node is being used to stay ahead of their deprecation schedule.
> ci: Update to `actions/checkout@v4`.

- Cargo.toml
- examples/example_process_collector.rs
- examples/example_push.rs
Hey,
I think we could use the [required features field](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-required-features-field) in the cargo.toml to improve the general experience / error messages when trying to run an example which requires a specific feature
> cargo/examples: add required-features annotations

- .github/workflows/rust.yml
- src/registry.rs
- static-metric/src/auto_flush_builder.rs
- static-metric/src/builder.rs
This fixes current CI failure on `master`:
```
error: package `clap v4.5.4` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.70.0
```
> ci: bump MSRV to fix test jobs

- src/macros.rs
This is a pedantic lint added in 1.73.0. Because it occurs inside a macro expansion, the lint is triggered from user code. The justification given by the lint definition is:
> Matching with `()` explicitly instead of `_` outlines the fact that
> the pattern contains no data. Also it would detect a type change that
> `_` would ignore.
Removing the lint requires a trivial change. It does introduce the possibility for compilation errors in the event the return type of the function currently returning `()` changes, but that seems like more of a benefit than a drawback. In these cases, it seems unlikely that the return type in question will change in the future.
The user experience can be seen by linting the examples:
```
% cargo +nightly clippy --examples -- -A clippy::all -W …
```
> Prevent `clippy::ignored_unit_patterns` in macro expansions

- CHANGELOG.md
- Cargo.toml
- Improvement: Add PullingGauge (#405)
- Improvement: Let cargo know which example requires which features (#511)
- Bug fix: Prevent `clippy::ignored_unit_patterns` in macro expansions (#497)
- Internal change: Add CI job for minimum toolchain (MSRV) (#467)
- Internal change: Update CI to `actions/checkout@v4` (#499)
- Internal change: Update dependencies
> prometheus: release 0.13.4

- static-metric/src/lib.rs
It should be `flashable` instead of `flash able`
>  static-metric: fix typos in docstrings

- .github/workflows/rust.yml
- Cargo.toml
This fixes the following CI failure:
```
error: rustc 1.78.0 is not supported by the following packages:
litemap@0.7.5 requires rustc 1.81
native-tls@0.2.14 requires rustc 1.80.0
native-tls@0.2.14 requires rustc 1.80.0
native-tls@0.2.14 requires rustc 1.80.0
zerofrom@0.1.6 requires rustc 1.81
```
Signed-off-by: Luca BRUNO <lucab@lucabruno.net>
> cargo: bump MSRV to 1.81

- CHANGELOG.md
- Cargo.toml
- API change: Use `AsRef<str>` for owned label values (#537)
- Improvement: Hashing improvements (#532)
- Dependency upgrade: Update `hyper` to 1.6 (#524)
- Dependency upgrade: Update `procfs` to 0.17 (#543)
- Dependency upgrade: Update `protobuf` to 3.7.2 for RUSTSEC-2024-0437 (#541)
- Dependency upgrade: Update `thiserror` to 2.0 (#534)
- Internal change: Fix LSP and Clippy warnings (#540)
- Internal change: Bump MSRV to 1.81 (#539)
- Documentation: Fix `register_histogram_vec_with_registry` docstring (#528)
- Documentation: Fix typos in static-metric docstrings (#479)
- Documentation: Add missing `protobuf` feature to README list (#531)
> prometheus: release 0.14.0

- src/registry.rs
Fix [manual contains (clippy linter warning)](https://rust-lang.github.io/rust-clippy/master/index.html#manual_contains)
> chore(registry): Fix linter warning

- src/histogram.rs
Leverage existing standard library method to simplify implementation. No changes to public API or MSRV.
> chore(histogram): Simplify code by using std lib method
